// From https://googlefonts.github.io/noto-emoji-animation/data/api.json

export type Icon = {
  name: string;
  version: number;
  popularity: number;
  codepoint: string;
  unsupported_families: never[];
  categories: string[];
  tags: string[];
  sizes_px: never[];
};

type Data = {
  host: string;
  asset_url_pattern: string;
  families: string[];
  icons: Icon[];
};

export const data: Data = {
  host: "",
  asset_url_pattern: "",
  families: ["Animated Emoji"],
  icons: [
    {
      name: "emoji_u1f600",
      version: 1,
      popularity: 411,
      codepoint: "1f600",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":smile:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f603",
      version: 1,
      popularity: 410,
      codepoint: "1f603",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":smile-with-big-eyes:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f604",
      version: 1,
      popularity: 409,
      codepoint: "1f604",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":grin:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f601",
      version: 1,
      popularity: 408,
      codepoint: "1f601",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":grinning:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f606",
      version: 1,
      popularity: 407,
      codepoint: "1f606",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":laughing:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f605",
      version: 1,
      popularity: 406,
      codepoint: "1f605",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":grin-sweat:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f602",
      version: 1,
      popularity: 405,
      codepoint: "1f602",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":joy:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f923",
      version: 1,
      popularity: 404,
      codepoint: "1f923",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":rofl:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f62d",
      version: 1,
      popularity: 403,
      codepoint: "1f62d",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":loudly-crying:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f609",
      version: 1,
      popularity: 402,
      codepoint: "1f609",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":wink:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f617",
      version: 1,
      popularity: 401,
      codepoint: "1f617",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":kissing:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f619",
      version: 1,
      popularity: 400,
      codepoint: "1f619",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":kissing-smiling-eyes:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f61a",
      version: 1,
      popularity: 399,
      codepoint: "1f61a",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":kissing-closed-eyes:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f618",
      version: 1,
      popularity: 398,
      codepoint: "1f618",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":kissing-heart:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f970",
      version: 1,
      popularity: 397,
      codepoint: "1f970",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":heart-face:", ":3-hearts:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f60d",
      version: 1,
      popularity: 396,
      codepoint: "1f60d",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":heart-eyes:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f929",
      version: 1,
      popularity: 395,
      codepoint: "1f929",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":star-struck:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f973",
      version: 1,
      popularity: 394,
      codepoint: "1f973",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":partying-face:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1fae0",
      version: 1,
      popularity: 393,
      codepoint: "1fae0",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":melting:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f643",
      version: 1,
      popularity: 392,
      codepoint: "1f643",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":upside-down-face:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f642",
      version: 1,
      popularity: 391,
      codepoint: "1f642",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":slightly-happy:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f972",
      version: 1,
      popularity: 390,
      codepoint: "1f972",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":happy-cry:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f979",
      version: 1,
      popularity: 389,
      codepoint: "1f979",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":holding-back-tears:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f60a",
      version: 1,
      popularity: 388,
      codepoint: "1f60a",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":blush:"],
      sizes_px: [],
    },
    {
      name: "emoji_u263a_fe0f",
      version: 1,
      popularity: 387,
      codepoint: "263a_fe0f",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":warm-smile:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f60c",
      version: 1,
      popularity: 386,
      codepoint: "1f60c",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":relieved:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f60f",
      version: 1,
      popularity: 385,
      codepoint: "1f60f",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":smirk:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f924",
      version: 1,
      popularity: 384,
      codepoint: "1f924",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":drool:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f60b",
      version: 1,
      popularity: 383,
      codepoint: "1f60b",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":yum:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f61b",
      version: 1,
      popularity: 382,
      codepoint: "1f61b",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":stuck-out-tongue:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f61d",
      version: 1,
      popularity: 381,
      codepoint: "1f61d",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":squinting-tongue:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f61c",
      version: 1,
      popularity: 380,
      codepoint: "1f61c",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":winky-tongue:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f92a",
      version: 1,
      popularity: 379,
      codepoint: "1f92a",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":zany-face:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f974",
      version: 1,
      popularity: 378,
      codepoint: "1f974",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":woozy:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f614",
      version: 1,
      popularity: 377,
      codepoint: "1f614",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":pensive:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f97a",
      version: 1,
      popularity: 376,
      codepoint: "1f97a",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":pleading:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f62c",
      version: 1,
      popularity: 375,
      codepoint: "1f62c",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":grimacing:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f611",
      version: 1,
      popularity: 374,
      codepoint: "1f611",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":expressionless:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f610",
      version: 1,
      popularity: 373,
      codepoint: "1f610",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":neutral-face:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f636",
      version: 1,
      popularity: 372,
      codepoint: "1f636",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":mouth-none:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f636_200d_1f32b_fe0f",
      version: 1,
      popularity: 371,
      codepoint: "1f636_200d_1f32b_fe0f",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":face-in-clouds:", ":lost:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1fae5",
      version: 1,
      popularity: 370,
      codepoint: "1fae5",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":dotted-line-face:", ":invisible:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f910",
      version: 1,
      popularity: 369,
      codepoint: "1f910",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":zipper-face:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1fae1",
      version: 1,
      popularity: 368,
      codepoint: "1fae1",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":salute:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f914",
      version: 1,
      popularity: 367,
      codepoint: "1f914",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":thinking-face:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f92b",
      version: 1,
      popularity: 366,
      codepoint: "1f92b",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":shushing-face:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1fae2",
      version: 1,
      popularity: 365,
      codepoint: "1fae2",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":hand-over-mouth:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f92d",
      version: 1,
      popularity: 364,
      codepoint: "1f92d",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":smiling-eyes-with-hand-over-mouth:", ":chuckling:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f971",
      version: 1,
      popularity: 363,
      codepoint: "1f971",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":yawn:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f917",
      version: 1,
      popularity: 362,
      codepoint: "1f917",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":hug-face:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1fae3",
      version: 1,
      popularity: 361,
      codepoint: "1fae3",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":peeking:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f631",
      version: 1,
      popularity: 360,
      codepoint: "1f631",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":screaming:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f928",
      version: 1,
      popularity: 359,
      codepoint: "1f928",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":raised-eyebrow:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f9d0",
      version: 1,
      popularity: 358,
      codepoint: "1f9d0",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":monocle:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f612",
      version: 1,
      popularity: 357,
      codepoint: "1f612",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":unamused:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f644",
      version: 1,
      popularity: 356,
      codepoint: "1f644",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":rolling-eyes:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f62e_200d_1f4a8",
      version: 1,
      popularity: 355,
      codepoint: "1f62e_200d_1f4a8",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":exhale:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f624",
      version: 1,
      popularity: 354,
      codepoint: "1f624",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":triumph:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f620",
      version: 1,
      popularity: 353,
      codepoint: "1f620",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":angry:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f621",
      version: 1,
      popularity: 352,
      codepoint: "1f621",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":rage:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f92c",
      version: 1,
      popularity: 351,
      codepoint: "1f92c",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":cursing:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f61e",
      version: 1,
      popularity: 350,
      codepoint: "1f61e",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":sad:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f613",
      version: 1,
      popularity: 349,
      codepoint: "1f613",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":sweat:", ":downcast:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f61f",
      version: 1,
      popularity: 348,
      codepoint: "1f61f",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":worried:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f625",
      version: 1,
      popularity: 347,
      codepoint: "1f625",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":concerned:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f622",
      version: 1,
      popularity: 346,
      codepoint: "1f622",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":cry:"],
      sizes_px: [],
    },
    {
      name: "emoji_u2639_fe0f",
      version: 1,
      popularity: 345,
      codepoint: "2639_fe0f",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":big-frown:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f641",
      version: 1,
      popularity: 344,
      codepoint: "1f641",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":frown:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1fae4",
      version: 1,
      popularity: 343,
      codepoint: "1fae4",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":diagonal-mouth:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f615",
      version: 1,
      popularity: 342,
      codepoint: "1f615",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":slightly-frowning:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f630",
      version: 1,
      popularity: 341,
      codepoint: "1f630",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":anxious-with-sweat:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f628",
      version: 1,
      popularity: 340,
      codepoint: "1f628",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":scared:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f627",
      version: 1,
      popularity: 339,
      codepoint: "1f627",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":anguished:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f626",
      version: 1,
      popularity: 338,
      codepoint: "1f626",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":gasp:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f62e",
      version: 1,
      popularity: 337,
      codepoint: "1f62e",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":mouth-open:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f62f",
      version: 1,
      popularity: 336,
      codepoint: "1f62f",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":surprised:", ":hushed:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f632",
      version: 1,
      popularity: 335,
      codepoint: "1f632",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":astonished:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f633",
      version: 1,
      popularity: 334,
      codepoint: "1f633",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":flushed:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f92f",
      version: 1,
      popularity: 333,
      codepoint: "1f92f",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":mind-blown:", ":exploding-head:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f616",
      version: 1,
      popularity: 332,
      codepoint: "1f616",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":scrunched-mouth:", ":confounded:", ":zigzag-mouth:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f623",
      version: 1,
      popularity: 331,
      codepoint: "1f623",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":scrunched-eyes:", ":persevering:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f629",
      version: 1,
      popularity: 330,
      codepoint: "1f629",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":weary:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f62b",
      version: 1,
      popularity: 329,
      codepoint: "1f62b",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":distraught:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f635",
      version: 1,
      popularity: 328,
      codepoint: "1f635",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":x-eyes:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f635_200d_1f4ab",
      version: 1,
      popularity: 327,
      codepoint: "1f635_200d_1f4ab",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":dizzy-face:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1fae8",
      version: 1,
      popularity: 326,
      codepoint: "1fae8",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":shaking-face:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f976",
      version: 1,
      popularity: 325,
      codepoint: "1f976",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":cold-face:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f975",
      version: 1,
      popularity: 324,
      codepoint: "1f975",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":hot-face:", ":sweat-face:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f922",
      version: 1,
      popularity: 323,
      codepoint: "1f922",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":sick:", ":nauseated:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f92e",
      version: 1,
      popularity: 322,
      codepoint: "1f92e",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":vomit:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f634",
      version: 1,
      popularity: 321,
      codepoint: "1f634",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":sleep:", ":tired:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f62a",
      version: 1,
      popularity: 320,
      codepoint: "1f62a",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":sleepy:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f927",
      version: 1,
      popularity: 319,
      codepoint: "1f927",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":sneeze:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f912",
      version: 1,
      popularity: 318,
      codepoint: "1f912",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":thermometer-face:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f915",
      version: 1,
      popularity: 317,
      codepoint: "1f915",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":bandage-face:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f637",
      version: 1,
      popularity: 316,
      codepoint: "1f637",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":mask:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f925",
      version: 1,
      popularity: 315,
      codepoint: "1f925",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":liar:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f607",
      version: 1,
      popularity: 314,
      codepoint: "1f607",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":halo:", ":innocent:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f920",
      version: 1,
      popularity: 313,
      codepoint: "1f920",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":cowboy:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f911",
      version: 1,
      popularity: 312,
      codepoint: "1f911",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":money-face:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f913",
      version: 1,
      popularity: 311,
      codepoint: "1f913",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":nerd-face:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f60e",
      version: 1,
      popularity: 310,
      codepoint: "1f60e",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":sunglasses-face:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f978",
      version: 1,
      popularity: 309,
      codepoint: "1f978",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":disguise:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f921",
      version: 1,
      popularity: 308,
      codepoint: "1f921",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":clown:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f608",
      version: 1,
      popularity: 307,
      codepoint: "1f608",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":imp-smile:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f47f",
      version: 1,
      popularity: 306,
      codepoint: "1f47f",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":imp-frown:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f47b",
      version: 1,
      popularity: 305,
      codepoint: "1f47b",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":ghost:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f480",
      version: 1,
      popularity: 304,
      codepoint: "1f480",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":skull:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f383",
      version: 1,
      popularity: 303,
      codepoint: "1f383",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":jack-o-lantern:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f4a9",
      version: 1,
      popularity: 302,
      codepoint: "1f4a9",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":poop:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f916",
      version: 1,
      popularity: 301,
      codepoint: "1f916",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":robot:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f47d",
      version: 1,
      popularity: 300,
      codepoint: "1f47d",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":alien:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f31e",
      version: 1,
      popularity: 299,
      codepoint: "1f31e",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":sun-with-face:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f31b",
      version: 1,
      popularity: 298,
      codepoint: "1f31b",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":moon-face-first-quarter:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f31c",
      version: 1,
      popularity: 297,
      codepoint: "1f31c",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":moon-face-last-quarter:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f648",
      version: 1,
      popularity: 296,
      codepoint: "1f648",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":see-no-evil-monkey:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f649",
      version: 1,
      popularity: 295,
      codepoint: "1f649",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":hear-no-evil-monkey:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f64a",
      version: 1,
      popularity: 294,
      codepoint: "1f64a",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":speak-no-evil-monkey:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f63a",
      version: 1,
      popularity: 293,
      codepoint: "1f63a",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":smiley-cat:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f638",
      version: 1,
      popularity: 292,
      codepoint: "1f638",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":smile-cat:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f639",
      version: 1,
      popularity: 291,
      codepoint: "1f639",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":joy-cat:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f63b",
      version: 1,
      popularity: 290,
      codepoint: "1f63b",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":heart-eyes-cat:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f63c",
      version: 1,
      popularity: 289,
      codepoint: "1f63c",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":smirk-cat:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f63d",
      version: 1,
      popularity: 288,
      codepoint: "1f63d",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":kissing-cat:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f640",
      version: 1,
      popularity: 287,
      codepoint: "1f640",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":scream-cat:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f63f",
      version: 1,
      popularity: 286,
      codepoint: "1f63f",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":crying-cat-face:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f63e",
      version: 1,
      popularity: 285,
      codepoint: "1f63e",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":pouting-cat:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f31f",
      version: 1,
      popularity: 284,
      codepoint: "1f31f",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":glowing-star:"],
      sizes_px: [],
    },
    {
      name: "emoji_u2728",
      version: 1,
      popularity: 283,
      codepoint: "2728",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":sparkles:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f4a5",
      version: 1,
      popularity: 282,
      codepoint: "1f4a5",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":collision:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f525",
      version: 1,
      popularity: 281,
      codepoint: "1f525",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":fire:", ":burn:", ":lit:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f4af",
      version: 1,
      popularity: 280,
      codepoint: "1f4af",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":100:", ":one-hundred:", ":hundred:", ":points:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f389",
      version: 1,
      popularity: 279,
      codepoint: "1f389",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":party-popper:"],
      sizes_px: [],
    },
    {
      name: "emoji_u2764_fe0f",
      version: 1,
      popularity: 278,
      codepoint: "2764_fe0f",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":red-heart:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f9e1",
      version: 1,
      popularity: 277,
      codepoint: "1f9e1",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":orange-heart:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f49b",
      version: 1,
      popularity: 276,
      codepoint: "1f49b",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":yellow-heart:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f49a",
      version: 1,
      popularity: 275,
      codepoint: "1f49a",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":green-heart:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1fa75",
      version: 1,
      popularity: 274,
      codepoint: "1fa75",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":light-blue-heart:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f499",
      version: 1,
      popularity: 273,
      codepoint: "1f499",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":blue-heart:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f49c",
      version: 1,
      popularity: 272,
      codepoint: "1f49c",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":purple-heart:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f90e",
      version: 1,
      popularity: 271,
      codepoint: "1f90e",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":brown-heart:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f5a4",
      version: 1,
      popularity: 270,
      codepoint: "1f5a4",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":black-heart:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1fa76",
      version: 1,
      popularity: 269,
      codepoint: "1fa76",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":grey-heart:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f90d",
      version: 1,
      popularity: 268,
      codepoint: "1f90d",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":white-heart:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1fa77",
      version: 1,
      popularity: 267,
      codepoint: "1fa77",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":pink-heart:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f498",
      version: 1,
      popularity: 266,
      codepoint: "1f498",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":cupid:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f49d",
      version: 1,
      popularity: 265,
      codepoint: "1f49d",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":gift-heart:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f496",
      version: 1,
      popularity: 264,
      codepoint: "1f496",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":sparkling-heart:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f497",
      version: 1,
      popularity: 263,
      codepoint: "1f497",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":heart-grow:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f493",
      version: 1,
      popularity: 262,
      codepoint: "1f493",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":beating-heart:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f49e",
      version: 1,
      popularity: 261,
      codepoint: "1f49e",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":revolving-hearts:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f495",
      version: 1,
      popularity: 260,
      codepoint: "1f495",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":two-hearts:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f48c",
      version: 1,
      popularity: 259,
      codepoint: "1f48c",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":love-letter:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f49f",
      version: 1,
      popularity: 258,
      codepoint: "1f49f",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":heart-box:"],
      sizes_px: [],
    },
    {
      name: "emoji_u2763_fe0f",
      version: 1,
      popularity: 257,
      codepoint: "2763_fe0f",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":heart-exclamation-point:"],
      sizes_px: [],
    },
    {
      name: "emoji_u2764_fe0f_200d_1fa79",
      version: 1,
      popularity: 256,
      codepoint: "2764_fe0f_200d_1fa79",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":bandaged-heart:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f494",
      version: 1,
      popularity: 255,
      codepoint: "1f494",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":broken-heart:"],
      sizes_px: [],
    },
    {
      name: "emoji_u2764_fe0f_200d_1f525",
      version: 1,
      popularity: 254,
      codepoint: "2764_fe0f_200d_1f525",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":fire-heart:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f48b",
      version: 1,
      popularity: 253,
      codepoint: "1f48b",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":kiss:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f463",
      version: 1,
      popularity: 252,
      codepoint: "1f463",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":footprints:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1fac0",
      version: 1,
      popularity: 251,
      codepoint: "1fac0",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":anatomical-heart:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1fa78",
      version: 1,
      popularity: 250,
      codepoint: "1fa78",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":blood:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f9a0",
      version: 1,
      popularity: 249,
      codepoint: "1f9a0",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":microbe:", ":virus:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f440",
      version: 1,
      popularity: 248,
      codepoint: "1f440",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":eyes:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f441_fe0f",
      version: 1,
      popularity: 247,
      codepoint: "1f441_fe0f",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":eye:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1fae6",
      version: 1,
      popularity: 246,
      codepoint: "1fae6",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":biting-lip:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f9bf",
      version: 1,
      popularity: 245,
      codepoint: "1f9bf",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":leg-mechanical:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f9be",
      version: 1,
      popularity: 244,
      codepoint: "1f9be",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":arm-mechanical:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f4aa",
      version: 1,
      popularity: 243,
      codepoint: "1f4aa",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":muscle:", ":flex:", ":bicep:", ":strong:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f4aa_1f3fb",
      version: 1,
      popularity: 242,
      codepoint: "1f4aa_1f3fb",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":muscle:", ":flex:", ":bicep:", ":strong:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f4aa_1f3fc",
      version: 1,
      popularity: 241,
      codepoint: "1f4aa_1f3fc",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":muscle:", ":flex:", ":bicep:", ":strong:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f4aa_1f3fd",
      version: 1,
      popularity: 240,
      codepoint: "1f4aa_1f3fd",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":muscle:", ":flex:", ":bicep:", ":strong:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f4aa_1f3fe",
      version: 1,
      popularity: 239,
      codepoint: "1f4aa_1f3fe",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":muscle:", ":flex:", ":bicep:", ":strong:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f4aa_1f3ff",
      version: 1,
      popularity: 238,
      codepoint: "1f4aa_1f3ff",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":muscle:", ":flex:", ":bicep:", ":strong:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f44f",
      version: 1,
      popularity: 237,
      codepoint: "1f44f",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":clap:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f44f_1f3fb",
      version: 1,
      popularity: 236,
      codepoint: "1f44f_1f3fb",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":clap:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f44f_1f3fc",
      version: 1,
      popularity: 235,
      codepoint: "1f44f_1f3fc",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":clap:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f44f_1f3fd",
      version: 1,
      popularity: 234,
      codepoint: "1f44f_1f3fd",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":clap:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f44f_1f3fe",
      version: 1,
      popularity: 233,
      codepoint: "1f44f_1f3fe",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":clap:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f44f_1f3ff",
      version: 1,
      popularity: 232,
      codepoint: "1f44f_1f3ff",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":clap:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f44d",
      version: 1,
      popularity: 231,
      codepoint: "1f44d",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":thumbs-up:", ":+1:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f44d_1f3fb",
      version: 1,
      popularity: 230,
      codepoint: "1f44d_1f3fb",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":thumbs-up:", ":+1:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f44d_1f3fc",
      version: 1,
      popularity: 229,
      codepoint: "1f44d_1f3fc",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":thumbs-up:", ":+1:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f44d_1f3fd",
      version: 1,
      popularity: 228,
      codepoint: "1f44d_1f3fd",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":thumbs-up:", ":+1:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f44d_1f3fe",
      version: 1,
      popularity: 227,
      codepoint: "1f44d_1f3fe",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":thumbs-up:", ":+1:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f44d_1f3ff",
      version: 1,
      popularity: 226,
      codepoint: "1f44d_1f3ff",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":thumbs-up:", ":+1:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f44e",
      version: 1,
      popularity: 225,
      codepoint: "1f44e",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":thumbs-down:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f44e_1f3fb",
      version: 1,
      popularity: 224,
      codepoint: "1f44e_1f3fb",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":thumbs-down:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f44e_1f3fc",
      version: 1,
      popularity: 223,
      codepoint: "1f44e_1f3fc",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":thumbs-down:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f44e_1f3fd",
      version: 1,
      popularity: 222,
      codepoint: "1f44e_1f3fd",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":thumbs-down:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f44e_1f3fe",
      version: 1,
      popularity: 221,
      codepoint: "1f44e_1f3fe",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":thumbs-down:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f44e_1f3ff",
      version: 1,
      popularity: 220,
      codepoint: "1f44e_1f3ff",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":thumbs-down:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f64c",
      version: 1,
      popularity: 219,
      codepoint: "1f64c",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":raising-hands:", ":hooray:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f64c_1f3fb",
      version: 1,
      popularity: 218,
      codepoint: "1f64c_1f3fb",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":raising-hands:", ":hooray:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f64c_1f3fc",
      version: 1,
      popularity: 217,
      codepoint: "1f64c_1f3fc",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":raising-hands:", ":hooray:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f64c_1f3fd",
      version: 1,
      popularity: 216,
      codepoint: "1f64c_1f3fd",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":raising-hands:", ":hooray:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f64c_1f3fe",
      version: 1,
      popularity: 215,
      codepoint: "1f64c_1f3fe",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":raising-hands:", ":hooray:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f64c_1f3ff",
      version: 1,
      popularity: 214,
      codepoint: "1f64c_1f3ff",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":raising-hands:", ":hooray:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f44b",
      version: 1,
      popularity: 213,
      codepoint: "1f44b",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":wave:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f44b_1f3fb",
      version: 1,
      popularity: 212,
      codepoint: "1f44b_1f3fb",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":wave:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f44b_1f3fc",
      version: 1,
      popularity: 211,
      codepoint: "1f44b_1f3fc",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":wave:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f44b_1f3fd",
      version: 1,
      popularity: 210,
      codepoint: "1f44b_1f3fd",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":wave:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f44b_1f3fe",
      version: 1,
      popularity: 209,
      codepoint: "1f44b_1f3fe",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":wave:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f44b_1f3ff",
      version: 1,
      popularity: 208,
      codepoint: "1f44b_1f3ff",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":wave:"],
      sizes_px: [],
    },
    {
      name: "emoji_u270c_fe0f",
      version: 1,
      popularity: 207,
      codepoint: "270c_fe0f",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":victory:", ":v:", ":peace-hand:"],
      sizes_px: [],
    },
    {
      name: "emoji_u270c_1f3fb",
      version: 1,
      popularity: 206,
      codepoint: "270c_1f3fb",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":victory:", ":v:", ":peace-hand:"],
      sizes_px: [],
    },
    {
      name: "emoji_u270c_1f3fc",
      version: 1,
      popularity: 205,
      codepoint: "270c_1f3fc",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":victory:", ":v:", ":peace-hand:"],
      sizes_px: [],
    },
    {
      name: "emoji_u270c_1f3fd",
      version: 1,
      popularity: 204,
      codepoint: "270c_1f3fd",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":victory:", ":v:", ":peace-hand:"],
      sizes_px: [],
    },
    {
      name: "emoji_u270c_1f3fe",
      version: 1,
      popularity: 203,
      codepoint: "270c_1f3fe",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":victory:", ":v:", ":peace-hand:"],
      sizes_px: [],
    },
    {
      name: "emoji_u270c_1f3ff",
      version: 1,
      popularity: 202,
      codepoint: "270c_1f3ff",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":victory:", ":v:", ":peace-hand:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f91e",
      version: 1,
      popularity: 201,
      codepoint: "1f91e",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":crossed-fingers:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f91e_1f3fb",
      version: 1,
      popularity: 200,
      codepoint: "1f91e_1f3fb",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":crossed-fingers:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f91e_1f3fc",
      version: 1,
      popularity: 199,
      codepoint: "1f91e_1f3fc",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":crossed-fingers:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f91e_1f3fd",
      version: 1,
      popularity: 198,
      codepoint: "1f91e_1f3fd",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":crossed-fingers:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f91e_1f3fe",
      version: 1,
      popularity: 197,
      codepoint: "1f91e_1f3fe",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":crossed-fingers:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f91e_1f3ff",
      version: 1,
      popularity: 196,
      codepoint: "1f91e_1f3ff",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":crossed-fingers:"],
      sizes_px: [],
    },
    {
      name: "emoji_u261d_fe0f",
      version: 1,
      popularity: 195,
      codepoint: "261d_fe0f",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":index-finger:"],
      sizes_px: [],
    },
    {
      name: "emoji_u261d_1f3fb",
      version: 1,
      popularity: 194,
      codepoint: "261d_1f3fb",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":index-finger:"],
      sizes_px: [],
    },
    {
      name: "emoji_u261d_1f3fc",
      version: 1,
      popularity: 193,
      codepoint: "261d_1f3fc",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":index-finger:"],
      sizes_px: [],
    },
    {
      name: "emoji_u261d_1f3fd",
      version: 1,
      popularity: 192,
      codepoint: "261d_1f3fd",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":index-finger:"],
      sizes_px: [],
    },
    {
      name: "emoji_u261d_1f3fe",
      version: 1,
      popularity: 191,
      codepoint: "261d_1f3fe",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":index-finger:"],
      sizes_px: [],
    },
    {
      name: "emoji_u261d_1f3ff",
      version: 1,
      popularity: 190,
      codepoint: "261d_1f3ff",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [":index-finger:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f64f",
      version: 1,
      popularity: 189,
      codepoint: "1f64f",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [
        ":folded-hands:",
        ":please:",
        ":pray:",
        ":hope:",
        ":wish:",
        ":thank-you:",
        ":high-five:",
      ],
      sizes_px: [],
    },
    {
      name: "emoji_u1f64f_1f3fb",
      version: 1,
      popularity: 188,
      codepoint: "1f64f_1f3fb",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [
        ":folded-hands:",
        ":please:",
        ":pray:",
        ":hope:",
        ":wish:",
        ":thank-you:",
        ":high-five:",
      ],
      sizes_px: [],
    },
    {
      name: "emoji_u1f64f_1f3fc",
      version: 1,
      popularity: 187,
      codepoint: "1f64f_1f3fc",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [
        ":folded-hands:",
        ":please:",
        ":pray:",
        ":hope:",
        ":wish:",
        ":thank-you:",
        ":high-five:",
      ],
      sizes_px: [],
    },
    {
      name: "emoji_u1f64f_1f3fd",
      version: 1,
      popularity: 186,
      codepoint: "1f64f_1f3fd",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [
        ":folded-hands:",
        ":please:",
        ":pray:",
        ":hope:",
        ":wish:",
        ":thank-you:",
        ":high-five:",
      ],
      sizes_px: [],
    },
    {
      name: "emoji_u1f64f_1f3fe",
      version: 1,
      popularity: 185,
      codepoint: "1f64f_1f3fe",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [
        ":folded-hands:",
        ":please:",
        ":pray:",
        ":hope:",
        ":wish:",
        ":thank-you:",
        ":high-five:",
      ],
      sizes_px: [],
    },
    {
      name: "emoji_u1f64f_1f3ff",
      version: 1,
      popularity: 184,
      codepoint: "1f64f_1f3ff",
      unsupported_families: [],
      categories: ["Smileys and emotions"],
      tags: [
        ":folded-hands:",
        ":please:",
        ":pray:",
        ":hope:",
        ":wish:",
        ":thank-you:",
        ":high-five:",
      ],
      sizes_px: [],
    },
    {
      name: "emoji_u1f483",
      version: 1,
      popularity: 183,
      codepoint: "1f483",
      unsupported_families: [],
      categories: ["People"],
      tags: [":dancer-woman:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f483_1f3fb",
      version: 1,
      popularity: 182,
      codepoint: "1f483_1f3fb",
      unsupported_families: [],
      categories: ["People"],
      tags: [":dancer-woman:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f483_1f3fc",
      version: 1,
      popularity: 181,
      codepoint: "1f483_1f3fc",
      unsupported_families: [],
      categories: ["People"],
      tags: [":dancer-woman:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f483_1f3fd",
      version: 1,
      popularity: 180,
      codepoint: "1f483_1f3fd",
      unsupported_families: [],
      categories: ["People"],
      tags: [":dancer-woman:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f483_1f3fe",
      version: 1,
      popularity: 179,
      codepoint: "1f483_1f3fe",
      unsupported_families: [],
      categories: ["People"],
      tags: [":dancer-woman:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f483_1f3ff",
      version: 1,
      popularity: 178,
      codepoint: "1f483_1f3ff",
      unsupported_families: [],
      categories: ["People"],
      tags: [":dancer-woman:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f339",
      version: 1,
      popularity: 177,
      codepoint: "1f339",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":rose:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f940",
      version: 1,
      popularity: 176,
      codepoint: "1f940",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":wilted-flower:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f342",
      version: 1,
      popularity: 175,
      codepoint: "1f342",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":fallen-leaf:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f331",
      version: 1,
      popularity: 174,
      codepoint: "1f331",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":plant:", ":seed:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f343",
      version: 1,
      popularity: 173,
      codepoint: "1f343",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":leaves:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f340",
      version: 1,
      popularity: 172,
      codepoint: "1f340",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":luck:", ":four-leaf-clover:"],
      sizes_px: [],
    },
    {
      name: "emoji_u2744_fe0f",
      version: 1,
      popularity: 171,
      codepoint: "2744_fe0f",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":snowflake:", ":winter:", ":cold:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f30b",
      version: 1,
      popularity: 170,
      codepoint: "1f30b",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":volcano:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f305",
      version: 1,
      popularity: 169,
      codepoint: "1f305",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":sunrise:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f304",
      version: 1,
      popularity: 168,
      codepoint: "1f304",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":sunrise-over-mountains:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f308",
      version: 1,
      popularity: 167,
      codepoint: "1f308",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":rainbow:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1fae7",
      version: 1,
      popularity: 166,
      codepoint: "1fae7",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":bubbles:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f30a",
      version: 1,
      popularity: 165,
      codepoint: "1f30a",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":ocean:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f32c_fe0f",
      version: 1,
      popularity: 164,
      codepoint: "1f32c_fe0f",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":wind-face:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f32a_fe0f",
      version: 1,
      popularity: 163,
      codepoint: "1f32a_fe0f",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":tornado:"],
      sizes_px: [],
    },
    {
      name: "emoji_u26a1",
      version: 1,
      popularity: 162,
      codepoint: "26a1",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":electricity:", ":zap:", ":lightning:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f4a7",
      version: 1,
      popularity: 161,
      codepoint: "1f4a7",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":droplet:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f327_fe0f",
      version: 1,
      popularity: 160,
      codepoint: "1f327_fe0f",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":rain-cloud:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f329_fe0f",
      version: 1,
      popularity: 159,
      codepoint: "1f329_fe0f",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":cloud-with-lightning:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f4ab",
      version: 1,
      popularity: 158,
      codepoint: "1f4ab",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":dizzy:"],
      sizes_px: [],
    },
    {
      name: "emoji_u2604_fe0f",
      version: 1,
      popularity: 157,
      codepoint: "2604_fe0f",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":comet:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f30d",
      version: 1,
      popularity: 156,
      codepoint: "1f30d",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":globe-showing-Europe-Africa:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f30e",
      version: 1,
      popularity: 155,
      codepoint: "1f30e",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":globe-showing-Americas:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f30f",
      version: 1,
      popularity: 154,
      codepoint: "1f30f",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":globe-showing-Asia-Australia:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f42e",
      version: 1,
      popularity: 153,
      codepoint: "1f42e",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":cow-face:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f984",
      version: 1,
      popularity: 152,
      codepoint: "1f984",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":unicorn:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f98e",
      version: 1,
      popularity: 151,
      codepoint: "1f98e",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":lizard:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f409",
      version: 1,
      popularity: 150,
      codepoint: "1f409",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":dragon:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f996",
      version: 1,
      popularity: 149,
      codepoint: "1f996",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":t-rex:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f995",
      version: 1,
      popularity: 148,
      codepoint: "1f995",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":dinosaur:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f422",
      version: 1,
      popularity: 147,
      codepoint: "1f422",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":turtle:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f40a",
      version: 1,
      popularity: 146,
      codepoint: "1f40a",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":crocodile:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f40d",
      version: 1,
      popularity: 145,
      codepoint: "1f40d",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":snake:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f438",
      version: 1,
      popularity: 144,
      codepoint: "1f438",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":frog:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f407",
      version: 1,
      popularity: 143,
      codepoint: "1f407",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":rabbit:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f400",
      version: 1,
      popularity: 142,
      codepoint: "1f400",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":rat:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f429",
      version: 1,
      popularity: 141,
      codepoint: "1f429",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":poodle:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f415",
      version: 1,
      popularity: 140,
      codepoint: "1f415",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":dog:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f9ae",
      version: 1,
      popularity: 139,
      codepoint: "1f9ae",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":guide-dog:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f415_200d_1f9ba",
      version: 1,
      popularity: 138,
      codepoint: "1f415_200d_1f9ba",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":service-dog:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f416",
      version: 1,
      popularity: 137,
      codepoint: "1f416",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":pig:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f40e",
      version: 1,
      popularity: 136,
      codepoint: "1f40e",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":racehorse:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1facf",
      version: 1,
      popularity: 135,
      codepoint: "1facf",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":donkey:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f402",
      version: 1,
      popularity: 134,
      codepoint: "1f402",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":ox:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f410",
      version: 1,
      popularity: 133,
      codepoint: "1f410",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":goat:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f998",
      version: 1,
      popularity: 132,
      codepoint: "1f998",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":kangaroo:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f405",
      version: 1,
      popularity: 131,
      codepoint: "1f405",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":tiger:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f412",
      version: 1,
      popularity: 130,
      codepoint: "1f412",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":monkey:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f98d",
      version: 1,
      popularity: 129,
      codepoint: "1f98d",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":gorilla:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f9a7",
      version: 1,
      popularity: 128,
      codepoint: "1f9a7",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":orangutan:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f43f_fe0f",
      version: 1,
      popularity: 127,
      codepoint: "1f43f_fe0f",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":chipmunk:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f9a6",
      version: 1,
      popularity: 126,
      codepoint: "1f9a6",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":otter:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f987",
      version: 1,
      popularity: 125,
      codepoint: "1f987",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":bat:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f426",
      version: 1,
      popularity: 124,
      codepoint: "1f426",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":bird:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f426_200d_2b1b",
      version: 1,
      popularity: 123,
      codepoint: "1f426_200d_2b1b",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":black-bird:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f413",
      version: 1,
      popularity: 122,
      codepoint: "1f413",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":rooster:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f423",
      version: 1,
      popularity: 121,
      codepoint: "1f423",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":hatching-chick:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f424",
      version: 1,
      popularity: 120,
      codepoint: "1f424",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":baby-chick:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f425",
      version: 1,
      popularity: 119,
      codepoint: "1f425",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":hatched-chick:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f985",
      version: 1,
      popularity: 118,
      codepoint: "1f985",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":eagle:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f54a_fe0f",
      version: 1,
      popularity: 117,
      codepoint: "1f54a_fe0f",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":peace:", ":dove:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1fabf",
      version: 1,
      popularity: 116,
      codepoint: "1fabf",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":goose:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f99a",
      version: 1,
      popularity: 115,
      codepoint: "1f99a",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":peacock:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f9ad",
      version: 1,
      popularity: 114,
      codepoint: "1f9ad",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":seal:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f988",
      version: 1,
      popularity: 113,
      codepoint: "1f988",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":shark:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f42c",
      version: 1,
      popularity: 112,
      codepoint: "1f42c",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":dolphin:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f433",
      version: 1,
      popularity: 111,
      codepoint: "1f433",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":whale:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f421",
      version: 1,
      popularity: 110,
      codepoint: "1f421",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":blowfish:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f980",
      version: 1,
      popularity: 109,
      codepoint: "1f980",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":crab:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f419",
      version: 1,
      popularity: 108,
      codepoint: "1f419",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":octopus:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1fabc",
      version: 1,
      popularity: 107,
      codepoint: "1fabc",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":jellyfish:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f577_fe0f",
      version: 1,
      popularity: 106,
      codepoint: "1f577_fe0f",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":spider:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f40c",
      version: 1,
      popularity: 105,
      codepoint: "1f40c",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":snail:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f41c",
      version: 1,
      popularity: 104,
      codepoint: "1f41c",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":ant:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f99f",
      version: 1,
      popularity: 103,
      codepoint: "1f99f",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":mosquito:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1fab3",
      version: 1,
      popularity: 102,
      codepoint: "1fab3",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":cockroach:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1fab0",
      version: 1,
      popularity: 101,
      codepoint: "1fab0",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":fly:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f41d",
      version: 1,
      popularity: 100,
      codepoint: "1f41d",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":bee:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f41e",
      version: 1,
      popularity: 99,
      codepoint: "1f41e",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":lady-bug:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f98b",
      version: 1,
      popularity: 98,
      codepoint: "1f98b",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":butterfly:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f41b",
      version: 1,
      popularity: 97,
      codepoint: "1f41b",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":bug:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1fab1",
      version: 1,
      popularity: 96,
      codepoint: "1fab1",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":worm:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f43e",
      version: 1,
      popularity: 95,
      codepoint: "1f43e",
      unsupported_families: [],
      categories: ["Animals and nature"],
      tags: [":paw prints:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f345",
      version: 1,
      popularity: 94,
      codepoint: "1f345",
      unsupported_families: [],
      categories: ["Food and drink"],
      tags: [":tomato:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f373",
      version: 1,
      popularity: 93,
      codepoint: "1f373",
      unsupported_families: [],
      categories: ["Food and drink"],
      tags: [":cooking:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f35d",
      version: 1,
      popularity: 92,
      codepoint: "1f35d",
      unsupported_families: [],
      categories: ["Food and drink"],
      tags: [":spaghetti:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f35c",
      version: 1,
      popularity: 91,
      codepoint: "1f35c",
      unsupported_families: [],
      categories: ["Food and drink"],
      tags: [":steaming-bowl:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f37f",
      version: 1,
      popularity: 90,
      codepoint: "1f37f",
      unsupported_families: [],
      categories: ["Food and drink"],
      tags: [":popcorn:"],
      sizes_px: [],
    },
    {
      name: "emoji_u2615",
      version: 1,
      popularity: 89,
      codepoint: "2615",
      unsupported_families: [],
      categories: ["Food and drink"],
      tags: [":hot-beverage:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f37b",
      version: 1,
      popularity: 88,
      codepoint: "1f37b",
      unsupported_families: [],
      categories: ["Food and drink"],
      tags: [":clinking-beer-mugs:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f942",
      version: 1,
      popularity: 87,
      codepoint: "1f942",
      unsupported_families: [],
      categories: ["Food and drink"],
      tags: [":clinking-glasses:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f37e",
      version: 1,
      popularity: 86,
      codepoint: "1f37e",
      unsupported_families: [],
      categories: ["Food and drink"],
      tags: [":bottle-with-popping-cork:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f377",
      version: 1,
      popularity: 85,
      codepoint: "1f377",
      unsupported_families: [],
      categories: ["Food and drink"],
      tags: [":wine-glass:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f379",
      version: 1,
      popularity: 84,
      codepoint: "1f379",
      unsupported_families: [],
      categories: ["Food and drink"],
      tags: [":tropical-drink:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f6a7",
      version: 1,
      popularity: 83,
      codepoint: "1f6a7",
      unsupported_families: [],
      categories: ["Travel and places"],
      tags: [":construction:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f6a8",
      version: 1,
      popularity: 82,
      codepoint: "1f6a8",
      unsupported_families: [],
      categories: ["Travel and places"],
      tags: [":police-car-light:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f6b2",
      version: 1,
      popularity: 81,
      codepoint: "1f6b2",
      unsupported_families: [],
      categories: ["Travel and places"],
      tags: [":bicycle:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f6f8",
      version: 1,
      popularity: 80,
      codepoint: "1f6f8",
      unsupported_families: [],
      categories: ["Travel and places"],
      tags: [":flying-saucer:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f680",
      version: 1,
      popularity: 79,
      codepoint: "1f680",
      unsupported_families: [],
      categories: ["Travel and places"],
      tags: [":rocket:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f6eb",
      version: 1,
      popularity: 78,
      codepoint: "1f6eb",
      unsupported_families: [],
      categories: ["Travel and places"],
      tags: [":airplane-departure:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f6ec",
      version: 1,
      popularity: 77,
      codepoint: "1f6ec",
      unsupported_families: [],
      categories: ["Travel and places"],
      tags: [":airplane-arrival:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f3a2",
      version: 1,
      popularity: 76,
      codepoint: "1f3a2",
      unsupported_families: [],
      categories: ["Travel and places"],
      tags: [":roller-coaster:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f3d5_fe0f",
      version: 1,
      popularity: 75,
      codepoint: "1f3d5_fe0f",
      unsupported_families: [],
      categories: ["Travel and places"],
      tags: [":camping:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f38a",
      version: 1,
      popularity: 74,
      codepoint: "1f38a",
      unsupported_families: [],
      categories: ["Activities and events"],
      tags: [":confetti-ball:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f388",
      version: 1,
      popularity: 73,
      codepoint: "1f388",
      unsupported_families: [],
      categories: ["Activities and events"],
      tags: [":balloon:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f382",
      version: 1,
      popularity: 72,
      codepoint: "1f382",
      unsupported_families: [],
      categories: ["Activities and events"],
      tags: [":birthday-cake:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f381",
      version: 1,
      popularity: 71,
      codepoint: "1f381",
      unsupported_families: [],
      categories: ["Activities and events"],
      tags: [":wrapped-gift:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f386",
      version: 1,
      popularity: 70,
      codepoint: "1f386",
      unsupported_families: [],
      categories: ["Activities and events"],
      tags: [":fireworks:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1fa85",
      version: 1,
      popularity: 69,
      codepoint: "1fa85",
      unsupported_families: [],
      categories: ["Activities and events"],
      tags: [":piñata:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1faa9",
      version: 1,
      popularity: 68,
      codepoint: "1faa9",
      unsupported_families: [],
      categories: ["Activities and events"],
      tags: [":mirror-ball:", ":disco-ball:"],
      sizes_px: [],
    },
    {
      name: "emoji_u26bd",
      version: 1,
      popularity: 67,
      codepoint: "26bd",
      unsupported_families: [],
      categories: ["Activities and events"],
      tags: [":soccer-ball:"],
      sizes_px: [],
    },
    {
      name: "emoji_u26be",
      version: 1,
      popularity: 66,
      codepoint: "26be",
      unsupported_families: [],
      categories: ["Activities and events"],
      tags: [":baseball:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f94e",
      version: 1,
      popularity: 65,
      codepoint: "1f94e",
      unsupported_families: [],
      categories: ["Activities and events"],
      tags: [":softball:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f3be",
      version: 1,
      popularity: 64,
      codepoint: "1f3be",
      unsupported_families: [],
      categories: ["Activities and events"],
      tags: [":tennis:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f3f8",
      version: 1,
      popularity: 63,
      codepoint: "1f3f8",
      unsupported_families: [],
      categories: ["Activities and events"],
      tags: [":badminton:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f94d",
      version: 1,
      popularity: 62,
      codepoint: "1f94d",
      unsupported_families: [],
      categories: ["Activities and events"],
      tags: [":lacrosse:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f3cf",
      version: 1,
      popularity: 61,
      codepoint: "1f3cf",
      unsupported_families: [],
      categories: ["Activities and events"],
      tags: [":cricket-game:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f3d1",
      version: 1,
      popularity: 60,
      codepoint: "1f3d1",
      unsupported_families: [],
      categories: ["Activities and events"],
      tags: [":field-hockey:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f3d2",
      version: 1,
      popularity: 59,
      codepoint: "1f3d2",
      unsupported_families: [],
      categories: ["Activities and events"],
      tags: [":ice-hockey:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f3af",
      version: 1,
      popularity: 58,
      codepoint: "1f3af",
      unsupported_families: [],
      categories: ["Activities and events"],
      tags: [":direct-hit:", ":target:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f94f",
      version: 1,
      popularity: 57,
      codepoint: "1f94f",
      unsupported_families: [],
      categories: ["Activities and events"],
      tags: [":flying-disc:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1fa83",
      version: 1,
      popularity: 56,
      codepoint: "1fa83",
      unsupported_families: [],
      categories: ["Activities and events"],
      tags: [":boomerang:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1fa81",
      version: 1,
      popularity: 55,
      codepoint: "1fa81",
      unsupported_families: [],
      categories: ["Activities and events"],
      tags: [":kite:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f3d3",
      version: 1,
      popularity: 54,
      codepoint: "1f3d3",
      unsupported_families: [],
      categories: ["Activities and events"],
      tags: [":ping-pong:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f3b3",
      version: 1,
      popularity: 53,
      codepoint: "1f3b3",
      unsupported_families: [],
      categories: ["Activities and events"],
      tags: [":bowling:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f3b2",
      version: 1,
      popularity: 52,
      codepoint: "1f3b2",
      unsupported_families: [],
      categories: ["Activities and events"],
      tags: [":die:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f3b0",
      version: 1,
      popularity: 51,
      codepoint: "1f3b0",
      unsupported_families: [],
      categories: ["Activities and events"],
      tags: [":slot-machine:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f4f8",
      version: 1,
      popularity: 50,
      codepoint: "1f4f8",
      unsupported_families: [],
      categories: ["Activities and events"],
      tags: [":camera-flash:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f3bb",
      version: 1,
      popularity: 49,
      codepoint: "1f3bb",
      unsupported_families: [],
      categories: ["Activities and events"],
      tags: [":violin:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f941",
      version: 1,
      popularity: 48,
      codepoint: "1f941",
      unsupported_families: [],
      categories: ["Activities and events"],
      tags: [":drum:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1fa87",
      version: 1,
      popularity: 47,
      codepoint: "1fa87",
      unsupported_families: [],
      categories: ["Activities and events"],
      tags: [":maracas:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f50b",
      version: 1,
      popularity: 46,
      codepoint: "1f50b",
      unsupported_families: [],
      categories: ["Objects"],
      tags: [":battery-full:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1faab",
      version: 1,
      popularity: 45,
      codepoint: "1faab",
      unsupported_families: [],
      categories: ["Objects"],
      tags: [":battery-low:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f4b8",
      version: 1,
      popularity: 44,
      codepoint: "1f4b8",
      unsupported_families: [],
      categories: ["Objects"],
      tags: [":money-with-wings:"],
      sizes_px: [],
    },
    {
      name: "emoji_u2696_fe0f",
      version: 1,
      popularity: 43,
      codepoint: "2696_fe0f",
      unsupported_families: [],
      categories: ["Objects"],
      tags: [":balance-scale:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f4a1",
      version: 1,
      popularity: 42,
      codepoint: "1f4a1",
      unsupported_families: [],
      categories: ["Objects"],
      tags: [":light-bulb:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f393",
      version: 1,
      popularity: 41,
      codepoint: "1f393",
      unsupported_families: [],
      categories: ["Objects"],
      tags: [":graduation-cap:"],
      sizes_px: [],
    },
    {
      name: "emoji_u2602_fe0f",
      version: 1,
      popularity: 40,
      codepoint: "2602_fe0f",
      unsupported_families: [],
      categories: ["Objects"],
      tags: [":umbrella:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f48e",
      version: 1,
      popularity: 39,
      codepoint: "1f48e",
      unsupported_families: [],
      categories: ["Objects"],
      tags: [":gem-stone:"],
      sizes_px: [],
    },
    {
      name: "emoji_u2699_fe0f",
      version: 1,
      popularity: 38,
      codepoint: "2699_fe0f",
      unsupported_families: [],
      categories: ["Objects"],
      tags: [":gear:"],
      sizes_px: [],
    },
    {
      name: "emoji_u270f_fe0f",
      version: 1,
      popularity: 37,
      codepoint: "270f_fe0f",
      unsupported_families: [],
      categories: ["Objects"],
      tags: [":pencil:"],
      sizes_px: [],
    },
    {
      name: "emoji_u23f0",
      version: 1,
      popularity: 36,
      codepoint: "23f0",
      unsupported_families: [],
      categories: ["Objects"],
      tags: [":alarm-clock:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f6ce_fe0f",
      version: 1,
      popularity: 35,
      codepoint: "1f6ce_fe0f",
      unsupported_families: [],
      categories: ["Objects"],
      tags: [":bellhop-bell:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f514",
      version: 1,
      popularity: 34,
      codepoint: "1f514",
      unsupported_families: [],
      categories: ["Objects"],
      tags: [":bell:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f52e",
      version: 1,
      popularity: 33,
      codepoint: "1f52e",
      unsupported_families: [],
      categories: ["Objects"],
      tags: [":crystal-ball:"],
      sizes_px: [],
    },
    {
      name: "emoji_u2648",
      version: 1,
      popularity: 32,
      codepoint: "2648",
      unsupported_families: [],
      categories: ["Symbols"],
      tags: [":Aries:"],
      sizes_px: [],
    },
    {
      name: "emoji_u2649",
      version: 1,
      popularity: 31,
      codepoint: "2649",
      unsupported_families: [],
      categories: ["Symbols"],
      tags: [":Taurus:"],
      sizes_px: [],
    },
    {
      name: "emoji_u264a",
      version: 1,
      popularity: 30,
      codepoint: "264a",
      unsupported_families: [],
      categories: ["Symbols"],
      tags: [":Gemini:"],
      sizes_px: [],
    },
    {
      name: "emoji_u264b",
      version: 1,
      popularity: 29,
      codepoint: "264b",
      unsupported_families: [],
      categories: ["Symbols"],
      tags: [":Cancer:"],
      sizes_px: [],
    },
    {
      name: "emoji_u264c",
      version: 1,
      popularity: 28,
      codepoint: "264c",
      unsupported_families: [],
      categories: ["Symbols"],
      tags: [":Leo:"],
      sizes_px: [],
    },
    {
      name: "emoji_u264d",
      version: 1,
      popularity: 27,
      codepoint: "264d",
      unsupported_families: [],
      categories: ["Symbols"],
      tags: [":Virgo:"],
      sizes_px: [],
    },
    {
      name: "emoji_u264e",
      version: 1,
      popularity: 26,
      codepoint: "264e",
      unsupported_families: [],
      categories: ["Symbols"],
      tags: [":Libra:"],
      sizes_px: [],
    },
    {
      name: "emoji_u264f",
      version: 1,
      popularity: 25,
      codepoint: "264f",
      unsupported_families: [],
      categories: ["Symbols"],
      tags: [":Scorpio:"],
      sizes_px: [],
    },
    {
      name: "emoji_u2650",
      version: 1,
      popularity: 24,
      codepoint: "2650",
      unsupported_families: [],
      categories: ["Symbols"],
      tags: [":Sagittarius:"],
      sizes_px: [],
    },
    {
      name: "emoji_u2651",
      version: 1,
      popularity: 23,
      codepoint: "2651",
      unsupported_families: [],
      categories: ["Symbols"],
      tags: [":Capricorn:"],
      sizes_px: [],
    },
    {
      name: "emoji_u2652",
      version: 1,
      popularity: 22,
      codepoint: "2652",
      unsupported_families: [],
      categories: ["Symbols"],
      tags: [":Aquarius:"],
      sizes_px: [],
    },
    {
      name: "emoji_u2653",
      version: 1,
      popularity: 21,
      codepoint: "2653",
      unsupported_families: [],
      categories: ["Symbols"],
      tags: [":Pisces:"],
      sizes_px: [],
    },
    {
      name: "emoji_u26ce",
      version: 1,
      popularity: 20,
      codepoint: "26ce",
      unsupported_families: [],
      categories: ["Symbols"],
      tags: [":Ophiuchus:"],
      sizes_px: [],
    },
    {
      name: "emoji_u2757",
      version: 1,
      popularity: 19,
      codepoint: "2757",
      unsupported_families: [],
      categories: ["Symbols"],
      tags: [":exclamation:", ":exclamation-mark:"],
      sizes_px: [],
    },
    {
      name: "emoji_u2753",
      version: 1,
      popularity: 18,
      codepoint: "2753",
      unsupported_families: [],
      categories: ["Symbols"],
      tags: [":question:", ":question-mark:", ":?:"],
      sizes_px: [],
    },
    {
      name: "emoji_u2049_fe0f",
      version: 1,
      popularity: 17,
      codepoint: "2049_fe0f",
      unsupported_families: [],
      categories: ["Symbols"],
      tags: [":exclamation-question-mark:", ":!?:"],
      sizes_px: [],
    },
    {
      name: "emoji_u203c_fe0f",
      version: 1,
      popularity: 16,
      codepoint: "203c_fe0f",
      unsupported_families: [],
      categories: ["Symbols"],
      tags: [":exclamation-double:", ":!!:"],
      sizes_px: [],
    },
    {
      name: "emoji_u274c",
      version: 1,
      popularity: 15,
      codepoint: "274c",
      unsupported_families: [],
      categories: ["Symbols"],
      tags: [":cross-mark:", ":x:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f198",
      version: 1,
      popularity: 14,
      codepoint: "1f198",
      unsupported_families: [],
      categories: ["Symbols"],
      tags: [":sos:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f4f4",
      version: 1,
      popularity: 13,
      codepoint: "1f4f4",
      unsupported_families: [],
      categories: ["Symbols"],
      tags: [":phone-off:"],
      sizes_px: [],
    },
    {
      name: "emoji_u2705",
      version: 1,
      popularity: 12,
      codepoint: "2705",
      unsupported_families: [],
      categories: ["Symbols"],
      tags: [":check-mark:", ":check-mark-green:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f195",
      version: 1,
      popularity: 11,
      codepoint: "1f195",
      unsupported_families: [],
      categories: ["Symbols"],
      tags: [":new:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f193",
      version: 1,
      popularity: 10,
      codepoint: "1f193",
      unsupported_families: [],
      categories: ["Symbols"],
      tags: [":free:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f199",
      version: 1,
      popularity: 9,
      codepoint: "1f199",
      unsupported_families: [],
      categories: ["Symbols"],
      tags: [":up!:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f192",
      version: 1,
      popularity: 8,
      codepoint: "1f192",
      unsupported_families: [],
      categories: ["Symbols"],
      tags: [":cool:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f6ae",
      version: 1,
      popularity: 7,
      codepoint: "1f6ae",
      unsupported_families: [],
      categories: ["Symbols"],
      tags: [":litter:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f3b6",
      version: 1,
      popularity: 6,
      codepoint: "1f3b6",
      unsupported_families: [],
      categories: ["Symbols"],
      tags: [":musical-notes:"],
      sizes_px: [],
    },
    {
      name: "emoji_u2795",
      version: 1,
      popularity: 5,
      codepoint: "2795",
      unsupported_families: [],
      categories: ["Symbols"],
      tags: [":plus-sign:", ":+:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f3c1",
      version: 1,
      popularity: 4,
      codepoint: "1f3c1",
      unsupported_families: [],
      categories: ["Flags"],
      tags: [":chequered-flag:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f6a9",
      version: 1,
      popularity: 3,
      codepoint: "1f6a9",
      unsupported_families: [],
      categories: ["Flags"],
      tags: [":triangular-flag:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f3f4",
      version: 1,
      popularity: 2,
      codepoint: "1f3f4",
      unsupported_families: [],
      categories: ["Flags"],
      tags: [":black-flag:"],
      sizes_px: [],
    },
    {
      name: "emoji_u1f3f3_fe0f",
      version: 1,
      popularity: 1,
      codepoint: "1f3f3_fe0f",
      unsupported_families: [],
      categories: ["Flags"],
      tags: [":white-flag:"],
      sizes_px: [],
    },
  ],
};
